App\Message\Register:
    properties:
        username:
            - NotBlank: ~
            - Email: ~
        password:
            - NotBlank: ~
            - Length: { min: 8, max: 50 }

App\Message\Invite:
    properties:
        userId:
            - NotBlank: ~
            - Uuid: ~
            - App\Validator\Constraints\UniqueConnection: ~
        message:
            - NotBlank: ~
