# Permanently redirect index to API doc
index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /api/docs
        permanent: true

api_login_check:
    path: /api/login_check
