resources:
    App\Entity\User:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
        attributes:
            normalization_context:
                groups: ['read']
            denormalization_context:
                groups: ['write']
