resources:
    App\Entity\User:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
        attributes:
            normalization_context:
                groups: ['read']
            denormalization_context:
                groups: ['write']

    App\Message\Register:
        collectionOperations:
            post:
                status: 200
                path: /register
        itemOperations: []
        attributes:
            messenger: true
            output: false
