resources:
    App\Entity\User:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
        attributes:
            normalization_context:
                groups: ['read']
            denormalization_context:
                groups: ['write']

    App\Message\Register:
        collectionOperations:
            post:
                status: 201
                path: /register
        itemOperations: []
        attributes:
            messenger: true
            output: App\Entity\User

    App\Message\Invite:
        collectionOperations:
            post:
                status: 200
                path: /invite
                security: is_granted('ROLE_USER')
        itemOperations: []
        attributes:
            messenger: true
            output: App\Entity\Connection
