resources:
    App\Entity\User:
        collectionOperations:
            user_connections:
                method: GET
                path: /users/{id}/connections
                controller: App\Controller\UserConnections
                read: false
        itemOperations:
            get: ~
        attributes:
            normalization_context:
                groups: ['read']

    App\Entity\Connection:
        collectionOperations: []
        itemOperations:
            get: ~
        attributes:
            normalization_context:
                groups: ['read']

    App\Message\Register:
        collectionOperations:
            post:
                status: 201
                path: /register
        itemOperations: []
        attributes:
            messenger: true
            output: App\Entity\User

    App\Message\Invite:
        collectionOperations:
            post:
                status: 200
                path: /invite
                security: is_granted('ROLE_USER')
        itemOperations: []
        attributes:
            messenger: true
            output: App\Entity\Connection
